
server:
  port: 2525

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${eureka_server_hostname:localhost}

  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    root: debug