server:
  port: 8002
  servlet:
    context-path: /customer-app

spring:
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/
    registerWithEureka: true
    enabled: true

  instance:
    hostname: ${customer_app_hostname:localhost}
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info

# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
