server:
  port: ${app_server_port:8001}
  servlet:
    context-path: /customer-app

spring:
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/
    enabled: true
    register-with-eureka: true

  instance:
    hostname: ${customer_app_hostname:localhost}
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info

# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
