server:
  port: 0
  servlet:
    context-path: /customer-app

spring:
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:2525/eureka/
    registerWithEureka: true
    enabled: true

  instance:
    hostname: ${customer_app_hostname:localhost}
    instance-id: ${spring.application.name}
    preferIpAddress: true

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
