server:
  port: 8000
  servlet:
    context-path: /spring-feign-eureka-server

spring:
  application:
    name: spring-feign-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/
    fetch-registry: true

logging:
  level:
    com.polovyi.ivan.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info