server:
  port: 8000
  servlet:
    context-path: /spring-feign-eureka-server

spring:
  application:
    name: spring-feign-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


  instance:
    hostname: ${spring_feign_client_hostname:localhost}
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    com.polovyi.ivan.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info